/**
 * Token Builder utilizing Style Dictionary 5.5.5
 *
 * Generates:
 * 1. antd.theme.ts (Ant Design 5.7.3 ThemeConfig with strictly typed number/color tokens)
 * 2. tokens.css (--d2c-* CSS variables for layout and custom styles)
 * 3. tokens.less (@d2c-* Less variables for backward-compatible compile-time imports)
 */

import StyleDictionary from "style-dictionary";
import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { createHash } from "node:crypto";
import type { ThemeConfig } from "antd";
import type { Diagnostic } from "../contracts/schema.js";

export interface TokenBuildOptions {
  tokenFilePath?: string;
  outputDir?: string;
}

export interface TokenBuildResult {
  success: boolean;
  artifacts: {
    antdThemePath: string;
    cssTokensPath: string;
    lessTokensPath: string;
  };
  hashes: {
    antdThemeHash: string;
    cssTokensHash: string;
    lessTokensHash: string;
  };
  diagnostics: Diagnostic[];
}

export async function buildTokens(options: TokenBuildOptions = {}): Promise<TokenBuildResult> {
  const tokenFile = resolve(options.tokenFilePath || "tooling/d2c/tokens/canonical-tokens.json");
  const outDir = resolve(options.outputDir || "tooling/d2c/tokens/dist");

  const rawJson = JSON.parse(readFileSync(tokenFile, "utf-8"));
  const diagnostics: Diagnostic[] = [];

  // Custom Formatter for Ant Design 5.7.3 ThemeConfig
  const antdThemeFormatter = ({ dictionary }: { dictionary: any }) => {
    const tokenMap: Record<string, string | number | boolean> = {};

    for (const token of dictionary.allTokens) {
      const keyPath = token.path.join(".");
      const val = token.$value !== undefined ? token.$value : token.value;

      // Explicit mapping to Ant Design 5 Global Seed Tokens
      if (keyPath === "color.primary") tokenMap.colorPrimary = String(val);
      else if (keyPath === "color.success") tokenMap.colorSuccess = String(val);
      else if (keyPath === "color.error") tokenMap.colorError = String(val);
      else if (keyPath === "color.bg.container") tokenMap.colorBgContainer = String(val);
      else if (keyPath === "color.bg.layout") tokenMap.colorBgLayout = String(val);
      else if (keyPath === "color.text.primary") tokenMap.colorText = String(val);
      else if (keyPath === "color.text.secondary") tokenMap.colorTextSecondary = String(val);
      else if (keyPath === "color.border") tokenMap.colorBorder = String(val);
      else if (keyPath === "borderRadius.base") {
        const n = Number(val);
        if (isNaN(n)) {
          diagnostics.push({
            code: "INVALID_NUMBER_TOKEN",
            message: `AntD borderRadius token received non-numeric value: ${val}`,
            severity: "ERROR",
          });
        }
        tokenMap.borderRadius = isNaN(n) ? 6 : n;
      } else if (keyPath === "fontSize.base") {
        const n = Number(val);
        if (isNaN(n)) {
          diagnostics.push({
            code: "INVALID_NUMBER_TOKEN",
            message: `AntD fontSize token received non-numeric value: ${val}`,
            severity: "ERROR",
          });
        }
        tokenMap.fontSize = isNaN(n) ? 14 : n;
      }
    }

    tokenMap.wireframe = false;

    return `/**
 * Ant Design 5.7.3 ThemeConfig
 * Generated by Antigravity D2C Toolchain from Canonical Tokens.
 * DO NOT EDIT DIRECTLY.
 */

import type { ThemeConfig } from "antd";

export const antdTheme: ThemeConfig = {
  token: ${JSON.stringify(tokenMap, null, 4)},
};

export default antdTheme;
`;
  };

  // Strict Token Value Formatter for CSS/Less
  function formatTokenValue(token: any, varType: "css" | "less"): string {
    const rawVal = token.$value !== undefined ? token.$value : token.value;
    const type = token.$type || token.type || "custom";

    if (rawVal === undefined || rawVal === null) {
      diagnostics.push({
        code: "UNDEFINED_TOKEN_VALUE",
        message: `Token at '${token.path.join(".")}' has undefined value`,
        severity: "ERROR",
        path: token.path.join("."),
      });
      return "unset";
    }

    // 1. Dimension tokens: append px only if pure number; retain string units (px, rem, em, %)
    if (["dimension", "spacing", "borderRadius", "borderWidth", "fontSize"].includes(type)) {
      if (typeof rawVal === "number") {
        return `${rawVal}px`;
      }
      return String(rawVal);
    }

    // 2. Duration tokens: append ms only if pure number; retain string units (ms, s)
    if (["duration", "transitionDuration"].includes(type)) {
      if (typeof rawVal === "number") {
        return `${rawVal}ms`;
      }
      return String(rawVal);
    }

    // 3. Unitless numeric tokens: NEVER append px (opacity, zIndex, fontWeight, number)
    if (["opacity", "zIndex", "fontWeight", "number"].includes(type)) {
      return String(rawVal);
    }

    // 4. Color tokens
    if (type === "color") {
      return String(rawVal);
    }

    // 5. Unsupported composite types
    if (["typography", "shadow", "gradient", "cubicBezier"].includes(type) || typeof rawVal === "object") {
      diagnostics.push({
        code: "UNSUPPORTED_DTCG_TYPE",
        message: `Token at '${token.path.join(".")}' of type '${type}' is an unsupported DTCG composite type without decomposition.`,
        severity: "WARNING",
        path: token.path.join("."),
        details: { type, value: rawVal },
      });
      return typeof rawVal === "object" ? JSON.stringify(rawVal) : String(rawVal);
    }

    return String(rawVal);
  }

  // Custom Formatter for --d2c-* CSS Variables with Collision Detection
  const cssVariablesFormatter = ({ dictionary }: { dictionary: any }) => {
    const lines: string[] = [
      "/**",
      " * Project Design Tokens (CSS Variables)",
      " * Generated by Antigravity D2C Toolchain from Canonical Tokens.",
      " * DO NOT EDIT DIRECTLY.",
      " */",
      ":root {",
    ];

    const emittedVars = new Map<string, string>();

    for (const token of dictionary.allTokens) {
      const varName = `--d2c-${token.path.join("-")}`;
      const tokenPath = token.path.join(".");

      if (emittedVars.has(varName)) {
        diagnostics.push({
          code: "CSS_VARIABLE_NAME_COLLISION",
          message: `CSS variable name collision: '${varName}' generated by both '${emittedVars.get(varName)}' and '${tokenPath}'`,
          severity: "ERROR",
          path: tokenPath,
        });
      } else {
        emittedVars.set(varName, tokenPath);
      }

      const val = formatTokenValue(token, "css");
      lines.push(`  ${varName}: ${val};`);
    }

    lines.push("}");
    lines.push("");
    return lines.join("\n");
  };

  // Custom Formatter for @d2c-* Less Variables
  const lessVariablesFormatter = ({ dictionary }: { dictionary: any }) => {
    const lines: string[] = [
      "/**",
      " * Project Design Tokens (Less Variables)",
      " * Generated by Antigravity D2C Toolchain from Canonical Tokens.",
      " * DO NOT EDIT DIRECTLY.",
      " */",
    ];

    for (const token of dictionary.allTokens) {
      const varName = `@d2c-${token.path.join("-")}`;
      const val = formatTokenValue(token, "less");
      lines.push(`${varName}: ${val};`);
    }

    lines.push("");
    return lines.join("\n");
  };

  mkdirSync(outDir, { recursive: true });

  const sd = new StyleDictionary({
    tokens: rawJson,
    hooks: {
      formats: {
        "antd/theme-ts": antdThemeFormatter,
        "css/d2c-variables": cssVariablesFormatter,
        "less/d2c-variables": lessVariablesFormatter,
      },
    },
    platforms: {
      antd: {
        buildPath: `${outDir}/`,
        files: [
          {
            destination: "antd.theme.ts",
            format: "antd/theme-ts",
          },
        ],
      },
      css: {
        buildPath: `${outDir}/`,
        files: [
          {
            destination: "tokens.css",
            format: "css/d2c-variables",
          },
        ],
      },
      less: {
        buildPath: `${outDir}/`,
        files: [
          {
            destination: "tokens.less",
            format: "less/d2c-variables",
          },
        ],
      },
    },
  });

  await sd.buildAllPlatforms();

  const antdThemePath = resolve(outDir, "antd.theme.ts");
  const cssTokensPath = resolve(outDir, "tokens.css");
  const lessTokensPath = resolve(outDir, "tokens.less");

  const antdContent = readFileSync(antdThemePath, "utf-8");
  const cssContent = readFileSync(cssTokensPath, "utf-8");
  const lessContent = readFileSync(lessTokensPath, "utf-8");

  const antdThemeHash = createHash("sha256").update(antdContent).digest("hex");
  const cssTokensHash = createHash("sha256").update(cssContent).digest("hex");
  const lessTokensHash = createHash("sha256").update(lessContent).digest("hex");

  return {
    success: diagnostics.filter((d) => d.severity === "ERROR").length === 0,
    artifacts: {
      antdThemePath,
      cssTokensPath,
      lessTokensPath,
    },
    hashes: {
      antdThemeHash,
      cssTokensHash,
      lessTokensHash,
    },
    diagnostics,
  };
}
